Repository CATcher-org/CATcher, pull requests merged in 2022-10, with the labels that each got.

#965 Add keyboard shortcuts
  src/app/shared/comment-editor/comment-editor.component.html
  src/app/shared/comment-editor/comment-editor.component.ts
Labels: s.ToMerge

#973 Add tests for session selection component
  tests/app/auth/session-selection/session-selection.component.spec.ts
Labels: s.ToReview, s.ToMerge

#955 Update angular to version 9
  angular.json
  package.json
  src/app/auth/profiles/json-parse-error-dialog/json-parse-error-dialog.component.ts
  src/app/auth/profiles/profiles.component.ts
  src/app/core/directives/form-disable-control.directive.ts
  src/app/core/guards/user-confirmation/user-confirmation.component.ts
  src/app/core/services/dialog.service.ts
  src/app/core/services/error-handling.service.ts
  src/app/core/services/repo-creator.service.ts
  src/app/core/services/session-fix-confirmation/session-fix-confirmation.component.ts
  src/app/shared/action-toasters/undo-action/undo-action.component.ts
  src/app/shared/comment-editor/comment-editor.component.ts
  src/app/shared/error-toasters/form-error/form-error.component.ts
  src/app/shared/error-toasters/general-message-error/general-message-error.component.ts
  src/app/shared/error-toasters/invalid-credentials-error/invalid-credentials-error.component.ts
  src/app/shared/error-toasters/toaster/toaster.component.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue-tables/issue-paginator.ts
  src/app/shared/issue-tables/issue-sorter.ts
  src/app/shared/issue-tables/issue-tables.component.ts
  src/app/shared/issue/assignee/assignee.component.ts
  src/app/shared/issue/conflict-dialog/conflict-dialog.component.ts
  src/app/shared/issue/description/description.component.ts
  src/app/shared/issue/duplicateOf/duplicate-of.component.ts
  src/app/shared/issue/issue-components.module.ts
  src/app/shared/label-definition-popup/label-definition-popup.component.ts
  src/app/shared/lib/marked.ts
  src/app/shared/material.module.ts
  src/app/shared/view-issue/issue-dispute/issue-dispute.component.ts
  src/app/shared/view-issue/new-team-response/conflict-dialog/conflict-dialog.component.ts
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
  src/app/shared/view-issue/team-response/team-response.component.ts
  src/app/shared/view-issue/tester-response/conflict-dialog/conflict-dialog.component.ts
  src/app/shared/view-issue/tester-response/tester-response.component.ts
  src/tsconfig.app.json
  src/typings.d.ts
  tests/app/shared/issue-tables/issue-paginator.spec.ts
  tests/app/shared/issue-tables/issue-sorter.spec.ts
  tests/app/shared/issue/description/description.component.spec.ts
  tests/app/shared/issue/title/title.component.spec.ts
Labels: s.ToReview, s.ToMerge

#985 Update cancel edit warning behaviour
  src/app/shared/issue/description/description.component.html
  src/app/shared/issue/description/description.component.ts
  src/app/shared/issue/title/title.component.html
  src/app/shared/issue/title/title.component.ts
Labels: s.ToReview

#979 Add logging for parse errors
  src/app/core/models/issue.model.ts
  src/app/core/models/templates/template.model.ts
  src/app/core/services/issue.service.ts
Labels: s.ToReview

#996 Add unit tests for error handling service
  tests/constants/error.constants.ts
  tests/services/error-handling.service.spec.ts
Labels: s.ToReview

#1020 Fix #1014 Tester responses: All bugs are marked as 'Faulty Issues'
  package.json
  src/app/core/models/templates/tester-response-template.model.ts
  tests/constants/githubcomment.constants.ts
Labels: s.ToMerge

#990 Add markdown toolbar
  package.json
  src/app/core/services/repo-creator.service.ts
  src/app/shared/comment-editor/comment-editor.component.html
  src/app/shared/comment-editor/comment-editor.module.ts
  src/app/shared/comment-editor/markdown-toolbar/markdown-toolbar.component.css
  src/app/shared/comment-editor/markdown-toolbar/markdown-toolbar.component.html
  src/app/shared/comment-editor/markdown-toolbar/markdown-toolbar.component.ts
  tests/app/shared/comment-editor/comment-editor.component.spec.ts
Labels: s.ToReview

#984 Add warning dialog box when cancelling edits for `team response` and `tester response`
  src/app/shared/view-issue/team-response/team-response.component.html
  src/app/shared/view-issue/team-response/team-response.component.ts
  src/app/shared/view-issue/tester-response/tester-response.component.html
  src/app/shared/view-issue/tester-response/tester-response.component.ts
Labels: s.ToReview

#983 Add tests for text insertor
  src/app/shared/comment-editor/upload-text-insertor.ts
  tests/app/shared/comment-editor/upload-text-insertor.spec.ts
Labels: s.ToReview
