Repository CATcher-org/CATcher, pull requests merged in 2022-04, with the labels that each got.

#910 Use coroutine parsers for Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  package.json
  src/app/core/models/templates/sections/common-parsers.model.ts
  src/app/core/models/templates/sections/issue-dispute-section-parser.model.ts
  src/app/core/models/templates/sections/moderation-section-parser.model.ts
  src/app/core/models/templates/sections/tester-response-section-parser.model.ts
  src/app/core/models/templates/team-accepted-template.model.ts
  src/app/core/models/templates/team-response-template.model.ts
  src/app/core/models/templates/template.model.ts
  src/app/core/models/templates/tester-response-template.model.ts
  src/app/core/models/templates/tutor-moderation-issue-template.model.ts
  src/app/core/models/templates/tutor-moderation-todo-template.model.ts
  tests/model/templates/sections/issue-dispute-section-parser.model.spec.ts
  tests/model/templates/sections/moderation-section-parser.model.spec.ts
  tests/model/templates/sections/tester-response-section-parser.model.spec.ts
  tests/model/templates/team-response-template.model.spec.ts
  tests/model/templates/tester-response-template.model.spec.ts
  tests/model/templates/tutor-moderation-issue-template.model.spec.ts
  tests/model/templates/tutor-moderation-todo-template.model.spec.ts
Labels: aspect-CodeQuality, s.ToMerge

#918 Upload multiple files on drag and drop
  src/app/shared/comment-editor/comment-editor.component.ts
Labels: s.ToMerge

#921 Fix duplicate select error message
  src/app/shared/issue/duplicateOf/duplicate-of.component.ts
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
Labels: s.ToMerge

#920 Integrate arcsecond parsers and remove Section
  src/app/core/models/issue.model.ts
  src/app/core/models/templates/section-parsers/common-parsers.model.ts
  src/app/core/models/templates/section-parsers/issue-dispute-section-parser.model.ts
  src/app/core/models/templates/section-parsers/moderation-section-parser.model.ts
  src/app/core/models/templates/section-parsers/tester-response-section-parser.model.ts
  src/app/core/models/templates/sections/duplicate-of-section.model.ts
  src/app/core/models/templates/sections/issue-dispute-section.model.ts
  src/app/core/models/templates/sections/moderation-section.model.ts
  src/app/core/models/templates/sections/section.model.ts
  src/app/core/models/templates/sections/tester-response-section.model.ts
  src/app/core/models/templates/team-accepted-template.model.ts
  src/app/core/models/templates/team-response-template.model.ts
  src/app/core/models/templates/template.model.ts
  src/app/core/models/templates/tester-response-template.model.ts
  src/app/core/models/templates/tutor-moderation-issue-template.model.ts
  src/app/core/models/templates/tutor-moderation-todo-template.model.ts
  src/app/core/models/users/admins.model.ts
  src/app/core/models/users/parsed-user-data.model.ts
  src/app/core/models/users/roles.model.ts
  src/app/core/models/users/students.model.ts
  src/app/core/models/users/tabulated-user-data.model.ts
  src/app/core/models/users/teams.model.ts
  src/app/core/models/users/tutors.model.ts
  src/app/core/services/data.service.ts
  tests/model/templates/sections/issue-dispute-section-parser.model.spec.ts
  tests/model/templates/sections/moderation-section-parser.model.spec.ts
  tests/model/templates/sections/tester-response-section-parser.model.spec.ts
  tests/model/templates/team-response-template.model.spec.ts
  tests/model/templates/tester-response-template.model.spec.ts
  tests/model/templates/tutor-moderation-issue-template.model.spec.ts
  tests/model/templates/tutor-moderation-todo-template.model.spec.ts
Labels: aspect-CodeQuality, s.ToMerge

#926 Hotfix: Remove Assignees Check
  src/app/core/services/github.service.ts
Labels: s.ToMerge

#932 Fix #931 Searching for issues assigned to multiple users
  src/app/shared/issue-tables/search-filter.ts
  tests/app/shared/issue-tables/search-filter.spec.ts
  tests/constants/githubissue.constants.ts
  tests/model/issue.model.spec.ts
Labels: category.Bug, s.ToReview

#917 Add a timed toast to undo deleting issues
  src/app/core/services/github.service.ts
  src/app/core/services/issue.service.ts
  src/app/shared/action-toasters/action-toasters.module.ts
  src/app/shared/action-toasters/undo-action/undo-action.component.html
  src/app/shared/action-toasters/undo-action/undo-action.component.ts
  src/app/shared/issue-tables/issue-tables.component.ts
  src/app/shared/shared.module.ts
Labels: s.ToMerge

#933 Remove assignee check API
  src/app/app.module.ts
  src/app/core/services/error-handling.service.ts
  src/app/core/services/factories/factory.issue.service.ts
  src/app/core/services/github.service.ts
  src/app/core/services/issue.service.ts
  src/app/shared/issue/assignee/assignee.component.ts
  tests/app/phase-team-response/issues-faulty/issues-faulty.component.spec.ts
  tests/app/phase-team-response/issues-pending/issues-pending.component.spec.ts
  tests/app/phase-team-response/issues-responded/issues-responded.component.spec.ts
  tests/app/shared/issue-tables/search-filter.spec.ts
  tests/app/shared/issue/assignee/assignee.component.spec.ts
Labels: s.ToMerge
