Repository CATcher-org/CATcher, pull requests merged in 2022-03, with the labels that each got.

#866 Add error handling for malformed issues / comments
  src/app/core/models/issue.model.ts
  src/app/core/models/templates/team-response-template.model.ts
  src/app/core/models/templates/tester-response-template.model.ts
  src/app/phase-team-response/issues-faulty/issues-faulty.component.ts
  src/app/phase-team-response/issues-pending/issues-pending.component.ts
  src/app/phase-tester-response/issue-faulty/issue-faulty.component.css
  src/app/phase-tester-response/issue-faulty/issue-faulty.component.html
  src/app/phase-tester-response/issue-faulty/issue-faulty.component.ts
  src/app/phase-tester-response/phase-tester-response.component.html
  src/app/phase-tester-response/phase-tester-response.module.ts
  src/app/shared/view-issue/parse-error/parse-error.component.css
  src/app/shared/view-issue/parse-error/parse-error.component.html
  src/app/shared/view-issue/parse-error/parse-error.component.ts
  src/app/shared/view-issue/parse-error/parse-error.module.ts
  src/app/shared/view-issue/view-issue.component.html
  src/app/shared/view-issue/view-issue.component.ts
  src/app/shared/view-issue/view-issue.module.ts
Labels: s.ToMerge

#891 Refactor colour constants in LabelService and CSS constants in LabelConstants
  src/app/core/services/label.service.ts
  tests/constants/label.constants.ts
Labels: s.ToMerge

#896 Update CATcher version to v3.4.2
  package.json
Labels: s.ToMerge

#899 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: s.ToMerge

#904 Abstract code to find comments that match a template to the Template class
  src/app/core/models/issue.model.ts
  src/app/core/models/templates/team-accepted-template.model.ts
  src/app/core/models/templates/team-response-template.model.ts
  src/app/core/models/templates/template.model.ts
  src/app/core/models/templates/tester-response-template.model.ts
  src/app/core/models/templates/tutor-moderation-todo-template.model.ts
Labels: aspect-CodeQuality, s.ToReview

#895 Add unit tests for Team Accepted Template
  tests/model/templates/team-accepted-template.model.spec.ts
Labels: aspect-Testing, s.ToMerge

#894 Improve Duplicate Issue Search in Team Response Phase
  package.json
  src/app/shared/issue/duplicateOf/duplicate-of.component.html
  src/app/shared/issue/duplicateOf/duplicate-of.component.ts
  src/app/shared/issue/issue-components.module.ts
  src/app/shared/view-issue/new-team-response/new-team-response.component.html
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
  src/app/shared/view-issue/new-team-response/new-team-response.module.ts
Labels: aspect-UIX, s.ToMerge

#913 Remove lower priority check for duplicate issues
  src/app/shared/issue/duplicateOf/duplicate-of.component.ts
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
Labels: s.ToMerge

#907 Add a link to report CATcher problems
  e2e/spec/login/login.e2e-spec.ts
  src/app/shared/layout/header.component.html
  src/app/shared/layout/header.component.ts
Labels: aspect-UIX, s.ToMerge
