Repository CATcher-org/CATcher, pull requests merged in 2023-02, with the labels that each got.

#1143 Fix lint warnings due to Deprecation of async & flatMap
  src/app/auth/auth.component.ts
  src/app/auth/confirm-login/confirm-login.component.ts
  src/app/core/services/github.service.ts
  src/app/core/services/githubevent.service.ts
  src/app/core/services/issue.service.ts
  src/app/core/services/label.service.ts
  src/app/core/services/mocks/mock.issue.service.ts
  src/app/core/services/phase.service.ts
  src/app/core/services/repo-creator.service.ts
  src/app/shared/issue-tables/IssuesDataTable.ts
  src/app/shared/issue/description/description.component.ts
  src/app/shared/view-issue/issue-dispute/issue-dispute.component.ts
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
  src/app/shared/view-issue/team-response/team-response.component.ts
  src/app/shared/view-issue/tester-response/tester-response.component.ts
  tests/app/auth/profiles/profiles.component.spec.ts
  tests/app/auth/session-selection/session-selection.component.spec.ts
  tests/app/shared/comment-editor/upload-text-insertor.spec.ts
  tests/app/shared/issue/assignee/assignee.component.spec.ts
  tests/app/shared/issue/duplicatedIssues/duplicated-issues.component.spec.ts
Labels: s.ToMerge

#1059 Reduce code duplication
  src/app/core/services/dialog.service.ts
  src/app/shared/issue/description/description.component.ts
  src/app/shared/issue/title/title.component.ts
  src/app/shared/view-issue/team-response/team-response.component.ts
  src/app/shared/view-issue/tester-response/tester-response.component.ts
Labels: s.ToMerge

#997 Use different separator when parsing
  src/app/core/models/templates/section-parsers/issue-dispute-section-parser.model.ts
  src/app/core/models/templates/section-parsers/moderation-section-parser.model.ts
  src/app/core/models/templates/section-parsers/tester-response-section-parser.model.ts
  tests/constants/githubcomment.constants.ts
  tests/constants/githubissue.constants.ts
  tests/model/templates/sections/issue-dispute-section-parser.model.spec.ts
  tests/model/templates/sections/moderation-section-parser.model.spec.ts
  tests/model/templates/sections/tester-response-section-parser.model.spec.ts
Labels: s.ToReview, s.ToMerge

#1139 Branch fix label
  src/app/core/models/issue.model.ts
  src/app/core/services/issue.service.ts
  src/app/core/services/label.service.ts
  src/app/core/services/mocks/mock.issue.service.ts
  src/app/shared/issue-tables/issue-tables-columns.ts
  src/app/shared/issue-tables/issue-tables.component.html
  src/app/shared/issue/duplicateOf/duplicate-of.component.ts
  src/app/shared/view-issue/new-team-response/conflict-dialog/conflict-dialog.component.html
  src/app/shared/view-issue/new-team-response/new-team-response.component.html
  src/app/shared/view-issue/new-team-response/new-team-response.component.ts
  src/app/shared/view-issue/view-issue.component.html
  tests/app/shared/issue-tables/search-filter.spec.ts
  tests/services/label.service.spec.ts
Labels: category.Bug

#1134 Add tool tip to indicate purpose of file button
  src/app/auth/profiles/profiles.component.html
Labels: s.ToMerge
